### ISSUE TITLE
Bug: APR mismatch for Velodrome stERN/ERN vault

### ISSUE THREAD

**Issue by defiglenn** [yearn/yearn.fi#370]
### What happened 🆘
**A clear and concise description of what the bug is.**
APR mismatch. User unsure which is correct APR. On yearn.fi vault list and when you click through to the vault it is showing APR as 47.37%. [Seafood also showing this.](https://seafood.yearn.watch/vault/0xa7B550B3A80361d8e47E07616dC42f04c655881b) However, when you click through to the strategies tab, you can see the vault has one strategy and the APR for it is 17.03%. 

### To Reproduce 🔂
See vault: https://yearn.fi/vaults/10/0xa7B550B3A80361d8e47E07616dC42f04c655881b
See strategies tab: https://yearn.fi/vaults/10/0xa7B550B3A80361d8e47E07616dC42f04c655881b?tab=strategies

### More 🔎
- Browser : chrome

**Comment by dudesahn** [comment]
I believe this is because of a pricing error for the stERN-ERN Pool token. 
- Using pricing data on Optimistic etherscan, the pool tokens are worth roughly ~$2 (realistically a bit more).
<img width="1181" alt="Screen Shot 2023-10-08 at 11 37 29 PM" src="https://github.com/yearn/yearn.fi/assets/23222916/55490447-27be-4ff9-a5ba-6146bdfd504f">

- UI is pricing them at a bit more than ~$1 each.
<img width="395" alt="Screen Shot 2023-10-08 at 11 36 59 PM" src="https://github.com/yearn/yearn.fi/assets/23222916/6e9a4dce-cace-443d-8a5b-c1fe33312070">

**Comment by jorndegen** [comment]
optimistic etherscan is not pricing the stERN in the pool token at all
https://optimistic.etherscan.io/address/0x4706e50fde911525e4b904c240056c4ea0884aa6

**Comment by dudesahn** [comment]
Seems like this might be impacting how the `boosted` info is displayed? The website knows the vault is boosted, but it's not showing up with the lightning emoji or special hover, though it shows up in the `Boosted` tab and also the `$OP BOOST` tab shows up on the vault detail page.

<img width="681" alt="Screen Shot 2023-10-14 at 5 31 23 PM" src="https://github.com/yearn/yearn.fi/assets/23222916/aa10d519-34cf-45f2-86f9-cd240096ec36">

**Comment by saltyfacu** [comment]
All this info comes from yearn-exporter. There will be an update today that would fix all this

**Comment by saltyfacu** [comment]
New APR calc's are online, please check that everything looks good

**Comment by jorndegen** [comment]
Looking good to me.  Thank you.
